stages:
  #  upstream
  # Merge requests
  - security
  - lint
  - tests
  - quality-gate

  #  downstream
  # Merge to main
  - deploy

default:
  artifacts:
    expire_in: 1 hour

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: maven
  paths:
    - .m2/repository

include:
  #  security
  - local: .gitlab/ci/security/java-common-sast.yml
  - local: .gitlab/ci/security/java-common-sbom.yml
  - local: .gitlab/ci/security/java-common-dependency-scanning.yml
  - local: .gitlab/ci/security/java-common-secret-detection.yml
  #  code
  - local: .gitlab/ci/code/java-common-code.yml